services:
  - type: web
    name: open-manus-ai
    env: python
    plan: starter
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run src/streamlit_app.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
    autoDeploy: true
    numInstances: 1
    healthCheckPath: /
    pythonVersion: 3.10.0
