services:
  - type: web
    name: open-manus-ai
    env: python
    plan: starter
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run src/main.py
    envVars:
      - key: OPENAI_API_KEY
        value: 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
      - key: TELEGRAM_BOT_TOKEN
        value: 7490395034:AAFNO1n6QzhVfUQWiE8a72MGx5Mr1RUWBHQ
    autoDeploy: true
    numInstances: 1
    healthCheckPath: /
    pythonVersion: 3.10.0
